batch_size: 16
checkpoint_dir: checkpoints/retinet_shapenet
data_dir: E:\dev\Shapenet_intrinsics
epochs: 100
gamma_imf: 1.0
gamma_r: 1.0
gamma_s: 1.0
image_height: 120
image_width: 160
log_dir: runs/retinet_shapenet
lr: 1.0e-05
mit_dir: data
momentum: 0.9
num_workers: 4
resume: null
save_freq: 5
seed: 42
use_dropout: true
val_on_mit: false
vis_freq: 5
weight_decay: 0.0005
