augment: true
batch_size: 16
checkpoint_dir: checkpoints/retinet
data_dir: E:/dev/intrinsics_final/intrinsics_final
epochs: 50
gamma_imf: 1.0
gamma_r: 1.0
gamma_s: 1.0
image_height: 120
image_width: 160
list_dir: E:/dev/intrinsics_final/intrinsics_final/train_list
log_dir: runs/retinet
lr: 1.0e-05
max_samples: null
momentum: 0.9
num_workers: 4
resume: null
save_freq: 5
seed: 42
use_dropout: true
val_dir: data
vis_freq: 5
weight_decay: 0.0005
